### ISSUE TITLE
[The Magic Highlighter] Color Preference Selection Default

### ISSUE THREAD

**Issue by Zolotkey** [herdworks/feedback#10]
### Product

The Magic Highlighter

### Subject

Automatically save my highlighted color preference.

### Feedback

When Selecting a color to highlight, the preference does not stay selected. It defaults back to Yellow. I would expect the color selected to stay selected until I change it again. 

### Context

https://user-images.githubusercontent.com/1952474/219767370-dc88c61d-e922-4252-998c-bf00681c2c91.mov

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
I had an idea about this while working on something else, so I started poking at this today and made enough progress that I know how to solve this now. And the best news is, I can make the preference sync across all devices (via iCloud). Looking forward to coming back to this soon! 🙌

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
