### ISSUE TITLE
[The Magic Highlighter] Numkeys 1–6 to change colours

### ISSUE THREAD

**Issue by Amparose** [herdworks/feedback#16]
### Product

The Magic Highlighter

### Subject

Numkeys 1–6 to change colours

### Feedback

Be nice to be able to go `⌘F` then `1–6` to change colours. Reaching for mouse is so passé 🙌🏻

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Love it! Great idea 👍🏽

**Comment by calebhailey** [comment]
I implemented this yesterday. Hoping to get it into TestFlight by the end of the week! 😊

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
