### ISSUE TITLE
[The Magic Highlighter] Make the Mac app icon have rounded corners

### ISSUE THREAD

**Issue by Eitot** [herdworks/feedback#20]
### Product

The Magic Highlighter

### Subject

Make the Mac app icon have rounded corners

### Feedback

The Mac app icon is currently square-shaped, which looks a bit unusual on macOS 11+ next to system icons and third-party extensions which follow [Apple's design guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#platform-considerations). This icon appears in Safari settings too.

### Context

<img width="227" alt="Screenshot 2023-04-01 at 10 50 18" src="https://user-images.githubusercontent.com/15073177/229276069-3a9c626b-ed7f-4ca4-a146-376186baf0a5.png">
<img width="344" alt="Screenshot 2023-04-01 at 10 40 02" src="https://user-images.githubusercontent.com/15073177/229275839-83dfc9c1-7baf-494e-98ac-b879aebe62c8.png">
<img width="485" alt="Screenshot 2023-04-01 at 10 41 11" src="https://user-images.githubusercontent.com/15073177/229275843-4c0d0340-cd2b-4bbd-afa5-9f66eb6036c0.png">

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
This bugs me as well. Thanks for reporting! I'm not a designer, so I wasn't even sure how to do this using the logo resources we got from the logo designer, but I've since learned how to do it for another project and just haven't got to it for The Magic Highlighter. Soon!

**Comment by jandamm** [comment]
On iOS this is actually how most icons look since the OS automatically crops the corners and replaces transparency with white.
On macOS you're allowed to have transparency in the app icon so you have to crop it yourself 🤷‍♂️

**Comment by calebhailey** [comment]
This is done and headed to TestFlight this afternoon! 😊 

<img width="1810" alt="Screenshot 2023-05-10 at 1 34 34 PM" src="https://github.com/herdworks/feedback/assets/141373/7d76ae3b-1dbe-44f8-936e-d738d53d9939">

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
