### ISSUE TITLE
[The Magic Highlighter] Add a toggle to disable magic highlights

### ISSUE THREAD

**Issue by calebhailey** [herdworks/feedback#29]
### Product

The Magic Highlighter

### Subject

Add a toggle to disable magic highlights

### Feedback

Some users have reported a desire to use The Magic Highlighter as a ⌘-F replacement _only_, without the magic highlights (i.e. without automatically highlighting search terms and phrases on search result web pages). 

Makes a ton of sense to me! In fact, this sort of [muscle memory](https://themagichighlighter.com/blog/muscle-memory/) use case (retraining your brain to ⌘-Shift-F instead of ⌘-F) has been the plan for The Magic Highlighter all along! ⚡ 

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Alternative title: KB shortcut only mode?

**Comment by calebhailey** [comment]
Made a TON of progress on this today (finally). Implemented a new configuration system that will synchronize config across devices, and started on an options screen to modify a bunch of what had previously been hardcoded logic, including the ability to disable magic highlights (the auto-highlighting behavior). With this option disabled, you'll be able to use The Magic Highlighter as a ⌘-F replacement only, without the automatic highlighting. ⚡

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/

**Comment by yrammos** [comment]
@calebhailey thank you for this immensely useful feature.

One small wrinkle: pressing Cmd-Option-F with the TMH popup open does not toggle the "thunder" icon. The effect of the keypress is not reflected in the UI unless the user closes and reopens the popup.
