### ISSUE TITLE
The Magic Highlighter & Duck Duck Go

### ISSUE THREAD

**Issue by chrismclay** [herdworks/feedback#34]
The latest release to iPad 0.7.0 seems to have broken support for Duck Duck Go.

Everything is working properly for Google and for Find on page, but not for Duck Duck Go.

I’ve tried resetting permissions, and restarting the iPad, but the problem continues.

**Comment by calebhailey** [comment]
Thanks for reporting! I have a fix for this headed to TestFlight (pending review). 👍

**Comment by jessearmstrong** [comment]
I'm also having this issue in Safari on Mac

**Comment by sgruby** [comment]
Any update on a release for this?

**Comment by calebhailey** [comment]
Version 0.7.1 (released last week) should resolve these issues! Sorry for the delay in getting this resolved!
