### ISSUE TITLE
[The Magic Highlighter] Extension breaks cmd+click on Kagi.com

### ISSUE THREAD

**Issue by jhogervorst** [herdworks/feedback#39]
### Product

The Magic Highlighter

### Subject

Extension breaks cmd+click on Kagi.com

### Feedback

When using <kbd>cmd</kbd> + click to open a Kagi search result in a new tab, it opens in the same tab when The Magic Highlighter extension is enabled. When I disable the extension, search results correctly open in a new tab. See a short video demonstrating the issue:

https://github.com/herdworks/feedback/assets/304065/1affd522-e11c-4a75-9439-43ae937ce79c

I think this wasn’t happening before, I think it broke in a recent update.

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Sorry for the slow reply here! This was fixed in the 0.7.1 release! 😊
