### ISSUE TITLE
[The Magic Highlighter] Impossible to open search results in new tab with Cmd-Click.

### ISSUE THREAD

**Issue by yrammos** [herdworks/feedback#42]
### Product

The Magic Highlighter

### Subject

Impossible to open search results in new tab with Cmd-Click.

### Feedback

Reproduction steps:

- Enable TMH (via the thunder toggle).
- Type keywords in the Safari address bar (with Google as default search engine).
- In the Google results page, command-click on any URL.
- Website opens in the same tab, not in a new one.

Repeating the process with TMH enabled results in a new tab, as expected.

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
I think I have a fix for this! Coming soon to TestFlight! 😊 

I figured out a way to handle click events without preventing the default behavior(s).

**Comment by jhogervorst** [comment]
@calebhailey Any news on the final release with this fix? It's quite annoying that I can't to <kbd>cmd+click</kbd> now, up to the point that I'm considering disabling The Magic Highlighter in my browser… 😅

**Comment by yrammos** [comment]
@calebhailey we would appreciate an update — and/or a TestFlight link. Thank you.

**Comment by calebhailey** [comment]
Sorry for the delay here - I've got a fix queued up for this week! Thanks for your patience! 🙏

**Comment by calebhailey** [comment]
0.7.1 was released last week and should fix this issue!
