### ISSUE TITLE
[The Magic Highlighter] Unable to work in Object Grid/Flex

### ISSUE THREAD

**Issue by peachysangria** [herdworks/feedback#43]
### Product

The Magic Highlighter

### Subject

Unable to work in Object Grid/Flex

### Feedback

I bought extension to be more efficient at work. My work interface consists of two Grid Objects in Flex Object, I must compare text fields inside each of them. Also page updates every time I send my result. When I add a word/phrase to highlighted phrases, extension can't find anything. It's only sensitive to header and footer. Is it possible to fix this?

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Hi there @peachysangria 👋 sorry for the slow response. Our company website makes pretty good use of CSS Grid and we're not having any issues there: https://herd.works/?cmdf=iphone+ipad+mac 

Do you have any public examples you can share? 

Thanks!
