### ISSUE TITLE
[The Magic Highlighter] Add a 'noise words' filter, or remember my selection

### ISSUE THREAD

**Issue by johnnydecimal** [herdworks/feedback#5]
### Product

The Magic Highlighter

### Subject

Add configurable removal of words like 'the', 'and', 'or', and so on

### Feedback

I generally don't want common words like 'the', 'and', and so on to be highlighted.

If I strike out these words in the toolbar icon, this preference is not remembered across sites. It would be good if it was.

Alternatively (or additionally?), provide a base set of words that can be ignored. This should probably be a toggle: either I want to ignore these words across all sites, or I don't.

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Thanks @johnnydecimal!!

**Comment by calebhailey** [comment]
Found a good resource for this: https://github.com/apache/lucene/blob/main/lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball/english_stop.txt 

While I'll be focusing on English initially, the Apache Lucene project has stop words for other languages as well: 

https://github.com/apache/lucene/tree/main/lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball

**Comment by calebhailey** [comment]
Made a TON of progress on this today (finally). Implemented a new configuration system that will synchronize config across devices, and started on an options screen to modify a bunch of what had previously been hardcoded logic, including a brand new list of "stop words". ⚡

**Comment by calebhailey** [comment]
Here's the English stop words list: 

<details><summary>Click to see the full list of 218 words...</summary>

```
"a",
"about",
"above",
"after",
"again",
"against",
"all",
"also",
"am",
"an",
"and",
"another",
"any",
"are",
"aren't",
"as",
"at",
"back",
"be",
"because",
"been",
"before",
"being",
"below",
"between",
"both",
"but",
"by",
"can't",
"cannot",
"could",
"couldn't",
"did",
"didn't",
"do",
"does",
"doesn't",
"doing",
"don't",
"down",
"during",
"each",
"even",
"ever",
"every",
"few",
"first",
"five",
"for",
"four",
"from",
"further",
"get",
"go",
"goes",
"had",
"hadn't",
"has",
"hasn't",
"have",
"haven't",
"having",
"he",
"he'd",
"he'll",
"he's",
"her",
"here",
"here's",
"hers",
"herself",
"high",
"him",
"himself",
"his",
"how",
"how's",
"however",
"i",
"i'd",
"i'll",
"i'm",
"i've",
"if",
"in",
"into",
"is",
"isn't",
"it",
"it's",
"its",
"itself",
"just",
"least",
"less",
"let's",
"like",
"long",
"made",
"make",
"many",
"me",
"more",
"most",
"mustn't",
"my",
"myself",
"never",
"new",
"no",
"nor",
"not",
"now",
"of",
"off",
"old",
"on",
"once",
"one",
"only",
"or",
"other",
"ought",
"our",
"ours",
"ourselves",
"out",
"over",
"own",
"put",
"said",
"same",
"say",
"says",
"second",
"see",
"seen",
"shan't",
"she",
"she'd",
"she'll",
"she's",
"should",
"shouldn't",
"since",
"so",
"some",
"still",
"such",
"take",
"than",
"that",
"that's",
"the",
"the",
"their",
"theirs",
"them",
"themselves",
"then",
"there",
"there's",
"these",
"they",
"they'd",
"they'll",
"they're",
"they've",
"this",
"those",
"three",
"through",
"to",
"too",
"two",
"under",
"until",
"up",
"us",
"very",
"was",
"wasn't",
"way",
"we",
"we'd",
"we'll",
"we're",
"we've",
"well",
"were",
"weren't",
"what",
"what's",
"when",
"when's",
"where",
"where's",
"whether",
"which",
"while",
"who",
"who's",
"whom",
"why",
"why's",
"with",
"won't",
"would",
"wouldn't",
"you",
"you'd",
"you'll",
"you're",
"you've",
"your",
"yours",
"yourself",
"yourselves"
```

</details>

I'm surprised at how many words are on the default list. Now I'm tempted to trim this down to something much shorter. 🤔

**Comment by calebhailey** [comment]
...but built-in (and customizeable) stop word filtering makes The Magic Highlighter **MUCH** better. 💪

**Comment by johnnydecimal** [comment]
I think that list is fine. I can't imagine any one of those words ever being the true subject of the thing that I was searching for.

**Comment by calebhailey** [comment]
Screenshots from an updated that is headed to TestFlight this week! 

<img width="1596" alt="Screenshot 2023-05-01 at 12 30 24 PM" src="https://user-images.githubusercontent.com/141373/235516344-6b87fb22-54aa-492f-afcb-32c42fd5ef7e.png">

<img width="1596" alt="Screenshot 2023-05-01 at 12 31 04 PM" src="https://user-images.githubusercontent.com/141373/235516407-95131122-ed57-427c-86e2-669da61806f0.png">

In this initial implementation, stop words are automatically disabled. Users will be able to modify the list of stop words.

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
