### ISSUE TITLE
[The Magic Highlighter] Add an on/off shortcut key

### ISSUE THREAD

**Issue by johnnydecimal** [herdworks/feedback#6]
### Product

The Magic Highlighter

### Subject

Add an on/off shortcut key

### Feedback

I'd like a shortcut key that turns TMH on/off for any given page. It should take immediate effect, i.e. not pop up the icon options and require me to do something else.

Ideally it would be user-configurable as I have many (many...) custom shortcuts already and would like to avoid conflict.

Behaviour:

- &lt;Keypress&gt;: turns TMH off *for this page*.
- &lt;Keypress&gt;: turns THM back on *for this page*.
- Close current page: behaviour forgotten.

I don't need a global on/off switch; I can just disable the extension if I want that.

### Code of Conduct

- [x] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Trying to decide what the KB shortcut should be for this... 

1. **`⌘-Shift-F + A`** 👍 
   In this case the "A" stands for "toggle all".
1. **`⌘-Shift-F + O`** ❤️
   In this case the "O" stands for "toggle on" and "toggle off".
1. **`⌘-Shift-F + J`** 🚀
   Because "J" is the [home row](https://www.quora.com/Why-do-the-F-and-J-keys-on-keyboards-have-bumps-on-them) rest position for the right hand, so it's a quick left-hand ➔ right-hand input? ⌘-Shift-F ➔ J feels like it would be fast.

Comment and/or vote with emoji reactions, 👍 , ❤️, or 🚀. I will vote for all three options to queue them up. 😊

**Comment by calebhailey** [comment]
Or maybe `⌘-Shift-F + P` for "Play/Pause"? The only thing I don't like about this option is that the P key isn't as convenient to reach. I like how Noir shows it's status with a "Pause" icon though, I think I'm gonna take inspiration from that. 

 
<img width="80" alt="CleanShot 2023-02-23 at 10 33 04@2x" src="https://user-images.githubusercontent.com/141373/220999106-b38f2221-2c3c-4655-82e0-9c6731b44257.png">

**Comment by johnnydecimal** [comment]
Oooh this is an interesting decision.

I can rule out `O` for on/off. That doesn’t feel familiar at all.

`A` makes sense, and is semantically memorable. I’ve already remembered it. All. All on, all off. Easy.

`J` I like from an ergonomic perspective, and I’m a nerd and touch-typist and Vim user so I get it. But will a ‘normal person’? Is a normal person using TMH? Got any stats, intel from reviews, so on? I think this is the key factor for me.

- - -

Okay I went with `A`. Semantics must rule. 🤘🏼

**Comment by johnnydecimal** [comment]
> I like how Noir shows it's status with a "Pause" icon though, I think I'm gonna take inspiration from that.

Agreed, that’s nice. But I wouldn’t go with `P` either. Ole stretchy-pinky-P is nobody’s favourite. Sorry, P.

**Comment by johnnydecimal** [comment]
Is the space bar an option? That feels familiar as a toggle? Or Return?

But I still like `A`.

**Comment by calebhailey** [comment]
@johnnydecimal spacebar is already used to toggle a selection made with ↑↓ (phrases) and ←→ (colors).

**Comment by calebhailey** [comment]
![CleanShot 2023-02-23 at 10 55 47](https://user-images.githubusercontent.com/141373/221004235-f7f2b8e5-24af-4b45-b652-e6e6e6411caa.gif)

**Comment by calebhailey** [comment]
This is available in TestFlight with version 0.6

**Comment by Amparose** [comment]
I would like to comment that this functionality should be a button in the pop up as well so I can turn off all on iOS (I don't normal have keeb connected to my phone). A search with many words is a PITA right now. 

Could be tapping "Highlighted Phrases" as that does nothing atm.

**Comment by calebhailey** [comment]
Thanks @Amparose, I agree. The keyboard shortcut was released with version 0.6.0, but I'm going to leave this open until I can add a toggle button.

**Comment by Eitot** [comment]
I'd like to have a button on the Mac version too.

An alternative UI would be to allow deselection of the currently-selected colour, similar to how Finder works with tags (I actually tried this in The Magic Highlighter when I didn't see a "disable all" toggle).
<img width="175" alt="Screenshot 2023-04-14 at 18 29 00" src="https://user-images.githubusercontent.com/15073177/232102913-cee21240-e4ff-4bcc-8d68-22f213d9433c.png"><img width="177" alt="Screenshot 2023-04-14 at 18 28 53" src="https://user-images.githubusercontent.com/15073177/232102942-910fb5a1-10d5-4cc1-ab0d-350fbe95857c.png">

**Comment by calebhailey** [comment]
I'm hoping to work on this one soon!

**Comment by docwindsor** [comment]
+1 This would be amazingly useful. I end up disabling the extension just to turn off the coloring.

Customized shortcut key would also be a huge help: unfortunately CMD+SHIFT-F is already hard-coded on some websites I have to use for work.

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
