### ISSUE TITLE
[The Magic Highlighter] Allow me to change the stored highlight colours

### ISSUE THREAD

**Issue by johnnydecimal** [herdworks/feedback#7]
### Product

The Magic Highlighter

### Subject

Allow me to change the stored highlight colours

### Feedback

The subject just about says it all.

I like the default yellow but would like to 'tone it down' a little. I just need a gentle highlight and find it too obtrusive.

Having 6 options for colouring is great. If I could modify them -- or even just one of them? -- that'd be better. :-)

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Made a TON of progress on this today (finally). Implemented a new configuration system that will synchronize config across devices, and started on an options screen to modify a bunch of what had previously been hardcoded logic, including user-defined highlight colors! ⚡

**Comment by calebhailey** [comment]
This is now available in the App Store! 

https://themagichighlighter.com/blog/most-wanted/
