### ISSUE TITLE
[The Magic Highlighter] Add support for Neeva search engine

### ISSUE THREAD

**Issue by Amparose** [herdworks/feedback#8]
### Product

The Magic Highlighter

### Subject

Add support for Neeva search engine

### Feedback

Support for [Neeva](https://neeva.com/), another privacy-focused search engine would be great.

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by calebhailey** [comment]
Thanks!!

**Comment by calebhailey** [comment]
Got this working! It should become available on TestFlight within the next 24 hours!

**Comment by calebhailey** [comment]
Released in 0.5.2
