### ISSUE TITLE
[The Magic Highlighter] Missing Version Number

### ISSUE THREAD

**Issue by Zolotkey** [herdworks/feedback#9]
### Product

The Magic Highlighter

### Subject

When Opening App on iOS version string is missing

### Feedback

When opening the app on iOS the app screen has great information however version is blank. It seems the String is not being populated in 0.4

### Context

App Version: 0.4
iOS Version: 16.3.1
Model: A2481 - iPhone 13 Mini

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

**Comment by Zolotkey** [comment]
![F8000402-73E5-4008-AE09-B57ED4828DEE](https://user-images.githubusercontent.com/1952474/219696911-549a997c-17a0-4fbd-bbf8-844fbd40f4eb.jpeg)

**Comment by calebhailey** [comment]
Thanks!

**Comment by calebhailey** [comment]
Released in 0.5.2
